### PR TITLE
Add capability to upload images

### PR DESCRIPTION
**Pull request by Chepheus**
Hello, sorry for my English.
I have to add capability to upload image because of default WYSIWYG it can.
I have another ideas for changing and want contribute to this repo in future.

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
Hello @Chepheus,

Thank you for this great contribution 🕺🏼 

It would solve the issue #1 reported by @edzai that I tried to solve without success.

Let me test it then I merge it asap 👍🏼 

Thibault

**Comment by thibaultduponchelle** [comment]
Back to you after a local test on latest q2a and unfortunately something appears to be buggy. 

This is what looks like my plugin *before* your change:
Screenshot from 2021-02-24 17-09-55

And this is what it looks like *with* your change:
Screenshot from 2021-02-24 17-10-33

If I remember correctly this is the problem I had when I tried to fix the upload image issue.

But your change is promising and even if I don't know what I can say to help you more, I will follow this closely and happily test again an updated version.

I'm also very happy to hear that you consider contributing more to this plugin. I think it's a cool plugin that solves nicely a real need but it not so much famous so far, even my previous broken version had more "stars" until very recently 😀 

And I'm cool and generally reactive.

**Comment by Chepheus** [comment]
I fix it. Please test it once more =)

**Comment by thibaultduponchelle** [comment]
Thank you a lot I will test it ASAP (probably tomorrow morning)

**Comment by thibaultduponchelle** [comment]
I tested once again, the upload image is working like a charm, but there is one more visual bug to fix.

Without the change:
Screenshot from 2021-02-26 09-50-02

With the change:
Screenshot from 2021-02-26 09-50-29

And also for comments:
Screenshot from 2021-02-26 09-51-50

I tried to quickly look at the sources, I see well a div `qa-a-item-clear` that seems to serve for this, but I don't know.

Could you please look at it?

I will happily test again 😄 👍🏼

**Comment by Chepheus** [comment]
Sorry about that, I fix this problem and hope that it was last problem =)
Anyway I am going to fix all problems of this branch and thank you for testing and writing detailed response for me =)

**Comment by thibaultduponchelle** [comment]
I tested and this is perfect, WELL DONE 👍🏼

**Comment by thibaultduponchelle** [comment]
I edited the plugin to announce a new version so that people using it can see "get v1.1.0" in the plugin admin page:
Screenshot from 2021-02-26 15-46-20

And I added your nick in the authors of the plugin so after an update you will see:
Screenshot from 2021-02-26 15-46-52

And I invited you as a collaborator to this plugin.

You can continue to submit pull requests that I review and test if you want but you will be able also to directly push to the repository and manage issue, merge pull request from others if any etc...

So welcome onboard, this plugin is also yours now!

**Comment by edzai** [comment]
Nice work guys, sorry been busy couldn't jump in. Well done for the work. Will also test it out.

**Comment by edzai** [comment]
Works well. Just added it on mathsgee.com - Bravo !!

**Pull request merged**
